AirShop.WebApp/Pages/AirGlassCatalogModel.cshtml.cs
using AirShop.ExternalServices.Services;
using AirShop.ExternalServices.Services.Rest;
using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AirShop.WebApp.Pages
{
    public class AirGlassCatalogModelModel : CatalogModelBase
    {
        public AirGlassCatalogModelModel(
            ShoppingCart shoppingCart,
            ReceiptService receiptService,
            IAirRestClient client)
            : base(shoppingCart, receiptService, client)
        {
        }
    }
}

AirShop.WebApp/Pages/AirPhoneCatalogModel.cshtml.cs
using AirShop.ExternalServices.Services;
using AirShop.ExternalServices.Services.Rest;
using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AirShop.WebApp.Pages
{
    public class AirPhoneCatalogModelModel : CatalogModelBase
    {
        public AirPhoneCatalogModelModel(
            ShoppingCart shoppingCart, 
            ReceiptService receiptService, 
            IAirRestClient client) 
            : base(shoppingCart, receiptService, client)
        {
        }
    }
}

AirShop.WebApp/Pages/AirTabCatalogModel.cshtml.cs
using AirShop.ExternalServices.Services;
using AirShop.ExternalServices.Services.Rest;
using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AirShop.WebApp.Pages
{
    public class AirTabCatalogModelModel : CatalogModelBase
    {
        public AirTabCatalogModelModel(
            ShoppingCart shoppingCart,
            ReceiptService receiptService,
            IAirRestClient client)
            : base(shoppingCart, receiptService, client)
        {
        }
    }
}

AirShop.WebApp/Pages/CatalogModelBase.cshtml.cs
using AirShop.DataAccess.Data.Models;
using AirShop.ExternalServices;
using AirShop.ExternalServices.Services;
using AirShop.ExternalServices.Services.Rest;

using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AirShop.WebApp.Pages
{
    public class CatalogModelBase : PageModel
    {
        private ShoppingCart _shoppingCart;
        private readonly ReceiptService _receiptService;
        private readonly IAirRestClient _client;

        public List<Product> Products { get; set; }

        public CatalogModelBase(ShoppingCart shoppingCart, ReceiptService receiptService, IAirRestClient client)
        {
            _shoppingCart = shoppingCart;
            _receiptService = receiptService;
            _client = client;

            Products = GetProducts().ToList();
        }

        public void OnGet()
        {
        }

        public IEnumerable<Product> GetProducts()
        {
            var products = _client.GetDevices();
            return products;
        }

        public IActionResult OnPostAddToCart(int productId)
        {
            var productToAdd = Products.FirstOrDefault(p => p.ProductId == productId);
            if (productToAdd != null)
            {
                _shoppingCart.AddToCart(productToAdd);
                Thread.Sleep(3000);
                return Page();
            }

            return Page();
        }


        public void RemoveFromCart(int productId)
        {
            _shoppingCart.RemoveFromCart(productId);
        }

        public void ClearCart()
        {
            _shoppingCart.ClearCart();
        }

        public int GetCartItemCount()
        {
            // Tutaj implementuj logikę pobierania liczby przedmiotów w koszyku
            // Może to być wywołanie metody w ShoppingCart lub pobranie wartości z cache, itp.
            return _shoppingCart.GetCartItemCount();
        }
    }
}

AirShop.WebApp/Pages/CheckoutPage.cshtml.cs
using AirShop.DataAccess.Data.Models;
using AirShop.ExternalServices.Entities;
using AirShop.ExternalServices.Interfaces;
using AirShop.ExternalServices.Services;
using AirShop.WebApp.ShopContext;
using AirShop.WebApp.Tools;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace AirShop.WebApp.Pages
{
    public class CheckoutPageModel : PageModel
    {
        private readonly ReceiptService _receiptService;
        private readonly IDocumentService _receiptDocumentService;
        private readonly DocumentHelper _helper;
        private readonly ShoppingCart _cart;

        public CheckoutPageModel(
            ReceiptService receiptService,
            IDocumentService receiptDocumentService,
            DocumentHelper helper,
            ShoppingCart cart)
        {
            _receiptService = receiptService;
            _receiptDocumentService = receiptDocumentService;
            _helper = helper;
            _cart = cart;

            //CheckoutInput = new CheckoutInputModel();
        }

        [BindProperty]
        public CheckoutInputModel CheckoutInput { get; set; }

        public IActionResult OnPost()
        {
            var listOfProducts = GetProductFromShoppingCart();
            
            if (CheckoutInput.GenerateInvoice)
            {
                var invoice = _helper.GenerateInvoice(CheckoutInput, listOfProducts);
                _receiptDocumentService.SaveDocument(invoice);
                return RedirectToPage("/Index");
            }
            //W ramach przelaczenia strony
            _receiptService.ReturnUserReceipt(listOfProducts, _helper.GetCustomer(CheckoutInput));
            _cart.ClearCart();
            return RedirectToPage("/Index");
        }

        private List<Product> GetProductFromShoppingCart()
        {
            return _cart.CartItems.ToList();
        }
    }

    public class CheckoutInputModel
    {
        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        [EmailAddress(ErrorMessage = "Nieprawid?owy format adresu email.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string City { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string HouseNumber { get; set; }

        public string ApartmentNumber { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        [RegularExpression(@"^\d{2}-\d{3}$", ErrorMessage = "Nieprawid?owy format kodu pocztowego. Wprowad? XX-XXX.")]
        public string ZipCode { get; set; }

        public bool GenerateInvoice { get; set; }

        public bool IsCompany { get; set; }

        public string NIP { get; set; }

        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string PaymentMethod { get; set; }
    }
}

AirShop.WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AirShop.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AirShop.WebApp/Pages/Index.cshtml.cs
using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AirShop.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ShopMainContext _shopMainContext;

        public IndexModel(ILogger<IndexModel> logger, ShopMainContext shopMainContext)
        {
            _logger = logger;
            _shopMainContext = shopMainContext;
        }

        public void OnGet()
        {
            ViewData["IsUserLoggedIn"] = _shopMainContext.IsUserLoggedIn;
            _logger.LogInformation("Is user logged? Result: "+_shopMainContext.IsUserLoggedIn.ToString());

            ViewData["LoggedInUserName"] = _shopMainContext.LoggedInUser?.Username;
        }
    }
}

AirShop.WebApp/Pages/LoginModel.cshtml.cs
using AirShop.ExternalServices.Entities;
using AirShop.ExternalServices.Services.Rest;
using AirShop.ExternalServices.Services.Rest.RestExceptions;
using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using User = AirShop.ExternalServices.Entities.User;

namespace AirShop.WebApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ShopMainContext _shopMainContext;
        private readonly IAirRestClient _client;

        public LoginModel(ShopMainContext shopMainContext, IAirRestClient client)
        {
            _shopMainContext = shopMainContext;
            _client = client;
            
            LoginInput = new LoginInputModel() 
            {
                Password = string.Empty,
                Username = string.Empty
            };
        }

        [BindProperty]
        public LoginInputModel LoginInput { get; set; }

        public IActionResult OnPost()
        {
            if (IsUserExist())
            {
                var loggedInUser = new User { Username = LoginInput.Username, Password = LoginInput.Password }; 
                _shopMainContext.LogInUser(loggedInUser);

                return RedirectToPage("/Index");
            }

            ModelState.AddModelError(string.Empty, "Invalid username or password.");
            return Page();
        }

        private bool IsUserExist()
        {
            try
            {
                var validUser = _client.GetUser(LoginInput.Username, LoginInput.Password);

                return !(validUser is null);
            }
            catch (RestClientException exception)
            {
                //Doda? mo?e jakie? logowanie czy co? podobnego
                return false;
            }
        }
    }

    public class LoginInputModel
    {
        [Required(ErrorMessage = "Please enter your username.")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please enter your password.")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Password must be at least 6 characters long.")]
        public string Password { get; set; }
    }
}

AirShop.WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AirShop.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AirShop.WebApp/Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AirShop.DataAccess.Data.Models;
using AirShop.ExternalServices.Services;
using AirShop.WebApp.ShopContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AirShop.WebApp.Pages
{
    public class ShoppingCartModel : PageModel
    {
        public List<ShoppingCartItem> ShoppingCartItems { get; set; }
        public decimal TotalPrice { get; set; }

        private readonly ShoppingCart _shoppingCart;
        private readonly ReceiptService _receiptService;

        public ShoppingCartModel(ShoppingCart shoppingCart, ReceiptService receiptService)
        {
            _shoppingCart = shoppingCart;
            _receiptService = receiptService;

            ShoppingCartItems = new List<ShoppingCartItem>();
        }

        public void OnGet()
        {
            foreach (var product in _shoppingCart.CartItems)
            {
                var item = new ShoppingCartItem()
                {
                    ProductId = product.ProductId,
                    ProductName = product.Name,
                    Price = product.Price,
                    SourceProduct = product,
                };
                ShoppingCartItems.Add(item);
            }

            TotalPrice = ShoppingCartItems.Sum(item => item.Price);
        }

        /*public IActionResult OnPostProceedCheckout()
        {
            try
            {
                _receiptService.ReturnUserReceipt(_shoppingCart.CartItems.ToList());
                return new JsonResult(new { success = true });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, error = ex.Message });
            }
        }*/
    }

    public class ShoppingCartItem
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public Product SourceProduct { get; set; }
    }
}

AirShop.WebApp/Pages/AirGlassCatalogModel.cshtml
@page
@model AirShop.WebApp.Pages.AirGlassCatalogModelModel
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>AirShop Catalog</title>
    <link rel="stylesheet" href="~/css/sklep.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style1.css" asp-append-version="true">
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
</head>
<body>



    <section class="shop" id="shop">
        <div class="container">
            @foreach (var product in Model.Products)
            {
                if (product.ProductType == DataAccess.Data.Models.ProductType.AirGlass)
                {
                    <div class="box">
                        <img src="@Url.Content(product.Image)">
                        <h4>@product.Name</h4>
                        <h5>@product.Price$</h5>
                        <form method="post" asp-page-handler="AddToCart" asp-route-productId="@product.ProductId">
                            <button class="addToCart" onclick="addToCart(@product.ProductId, event)">Dodaj do koszyka</button>
                        </form>
                    </div>
                }
            }
        </div>
    </section>

    <script>async function FetchProducts() {
            try {
                // Call your C# method to get the products
                //var products = await DotNet.invokeMethodAsync('AirShop.WebApp.Pages', 'GetProducts');

                // Add products to the table
                //products.forEach(product => AddProductToTable(product));
            } catch (error) {
                console.error('Error:', error);
            }
        }</script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @section Scripts {
        <script>
            function addToCart(productId, productName) {
                var url = '@Url.Page("/AirGlassCatalogModel", "OnPostAddToCart")';

                // Wywołujemy metodę AddToCart z modelu za pomocą JavaScript
                console.log("Start");
                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ productId: productId })
                });
                console.log("stop");



                Swal.fire({
                    icon: 'success',
                    title: `Produkt został dodany do koszyka!`,
                    showConfirmButton: false,
                    timer: 1500
                });

            }
        </script>
    }
</body>
</html>

AirShop.WebApp/Pages/AirPhoneCatalogModel.cshtml
@page
@model AirShop.WebApp.Pages.AirPhoneCatalogModelModel
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>AirShop Catalog</title>
    <link rel="stylesheet" href="~/css/sklep.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style1.css" asp-append-version="true">
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
</head>
<body>

    <!--ShoppingCart icon, trzeba dodac gdzies tutaj ikone z koszykiem-->

    <section class="shop" id="shop">
        <div class="container">
            @foreach (var product in Model.Products)
            {
                if (product.ProductType == DataAccess.Data.Models.ProductType.AirPhone)
                {
                    <div class="box">
                        <img src="@Url.Content(product.Image)">
                        <h4>@product.Name</h4>
                        <h5>@product.Price$</h5>
                        <form method="post" asp-page-handler="AddToCart" asp-route-productId="@product.ProductId">
                            <button class="addToCart" onclick="addToCart(@product.ProductId, event)">Dodaj do koszyka</button>
                        </form>
                    </div>
                }
            }
        </div>
    </section>

    <script>
        async function FetchProducts() {
            try {
                // Call your C# method to get the products
                //var products = await DotNet.invokeMethodAsync('AirShop.WebApp.Pages', 'GetProducts');

                // Add products to the table
                //products.forEach(product => AddProductToTable(product));
            } catch (error) {
                console.error('Error:', error);
            }
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @section Scripts {
        <script>
            function addToCart(productId, productName) {
                var url = '@Url.Page("/AirPhoneCatalogModel", "OnPostAddToCart")';

                // Wywołujemy metodę AddToCart z modelu za pomocą JavaScript
                console.log("Start");
                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ productId: productId })
                });
                console.log("stop");

                

                Swal.fire({
                    icon: 'success',
                    title: `Produkt został dodany do koszyka!`,
                    showConfirmButton: false,
                    timer: 1500
                });

            }
        </script>
    }
</body>
</html>

AirShop.WebApp/Pages/AirTabCatalogModel.cshtml
@page
@model AirShop.WebApp.Pages.AirTabCatalogModelModel
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>AirShop Catalog</title>
    <link rel="stylesheet" href="~/css/sklep.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style1.css" asp-append-version="true">
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
</head>
<body>

    <!--ShoppingCart icon, trzeba dodac gdzies tutaj ikone z koszykiem-->

    <section class="shop" id="shop">
        <div class="container">
            @foreach (var product in Model.Products)
            {
                if (product.ProductType == DataAccess.Data.Models.ProductType.AirTab)
                {
                    <div class="box">
                        <img src="@Url.Content(product.Image)">
                        <h4>@product.Name</h4>
                        <h5>@product.Price$</h5>
                        <form method="post" asp-page-handler="AddToCart" asp-route-productId="@product.ProductId">
                            <button class="addToCart" onclick="addToCart(@product.ProductId, event)">Dodaj do koszyka</button>
                        </form>
                    </div>
                }
            }
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @section Scripts {
        <script>
            function addToCart(productId, productName) {
                var url = '@Url.Page("/AirPhoneCatalogModel", "OnPostAddToCart")';

                // Wywołujemy metodę AddToCart z modelu za pomocą JavaScript
                console.log("Start");
                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ productId: productId })
                });
                console.log("stop");



                Swal.fire({
                    icon: 'success',
                    title: `Produkt został dodany do koszyka!`,
                    showConfirmButton: false,
                    timer: 1500
                });

            }
        </script>
    }
</body>
</html>

AirShop.WebApp/Pages/CatalogModelBase.cshtml
@page
@model AirShop.WebApp.Pages.CatalogModelBase
@{
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>AirShop Catalog</title>
    <link rel="stylesheet" href="~/css/sklep.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style1.css" asp-append-version="true">
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
</head>
<body>

    <!--ShoppingCart icon, trzeba dodac gdzies tutaj ikone z koszykiem-->

    <section class="shop" id="shop">
        <div class="container">
            @foreach (var product in Model.Products)
            {
                <div class="box">
                    <!--<img src="">-->
                    <h4>@product.Name</h4>
                    <h5>@product.Price$</h5>
                    <button class="addToCart" onclick="addToCart(@product.ProductId)">
                        Dodaj do koszyka
                    </button>
                </div>
            }
        </div>
    </section>

    <script>async function FetchProducts() {
            try {
                // Call your C# method to get the products
                //var products = await DotNet.invokeMethodAsync('AirShop.WebApp.Pages', 'GetProducts');

                // Add products to the table
                //products.forEach(product => AddProductToTable(product));
            } catch (error) {
                console.error('Error:', error);
            }
        }

        //function AddProductToTable(product) {
        //    var tableBody = document.getElementById("productBody");
        //    var row = tableBody.insertRow();

            // Insert cells with product data
         //   var cell1 = row.insertCell(0);
         //   var cell2 = row.insertCell(1);
           // var cell3 = row.insertCell(2);
            //var cell4 = row.insertCell(3);
            //var cell5 = row.insertCell(4);
            //var cell6 = row.insertCell(5);

            //cell1.innerHTML = product.productId;
            //cell2.innerHTML = product.name;
            //cell3.innerHTML = product.value;
            //cell4.innerHTML = product.vat;
            //cell5.innerHTML = product.price;
            //cell6.innerHTML = product.discount;
        }

        // Fetch and display existing products on page load
       </script>
     <script>
            function addToCart(productId, event) {
                event.preventDefault(); // Zatrzymaj domyślne zachowanie formularza

                // Wywołaj metodę AddToCart z modelu
                DotNet.invokeMethodAsync('AirShop.WebApp.Pages', 'AddToCart', productId);

        </script>
</body>
</html>

AirShop.WebApp/Pages/CheckoutPage.cshtml
@page
@model CheckoutPageModel
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Checkout</title>
    <link rel="stylesheet" href="~/css/style1.css" asp-append-version="true" />
</head>
<body>
    <h2>Checkout</h2>

    <section class="checkout" id="checkout">
        <div class="container">

            <form method="post">
                <div class="form-group">
                    <label for="FirstName">First Name:</label>
                    <input class="input" type="text" id="FirstName" name="FirstName" asp-for="CheckoutInput.FirstName" />
                    <span asp-validation-for="CheckoutInput.FirstName"></span>
                </div>

                <div class="form-group">
                    <label for="LastName">Last Name:</label>
                    <input class="input" type="text" id="LastName" name="LastName" asp-for="CheckoutInput.LastName" />
                    <span asp-validation-for="CheckoutInput.LastName"></span>
                </div>

                <div class="form-group">
                    <label for="Email">Email:</label>
                    <input class="input" type="text" id="Email" name="Email" asp-for="CheckoutInput.Email" />
                    <span asp-validation-for="CheckoutInput.Email"></span>
                </div>

                <div class="form-group">
                    <label for="Street">Street:</label>
                    <input class="input" type="text" id="Street" name="Street" asp-for="CheckoutInput.Street" />
                    <span asp-validation-for="CheckoutInput.Street"></span>
                </div>

                <div class="form-group">
                    <label for="City">City:</label>
                    <input class="input" type="text" id="City" name="City" asp-for="CheckoutInput.City" />
                    <span asp-validation-for="CheckoutInput.City"></span>
                </div>

                <div class="form-group">
                    <label for="HouseNumber">House Number:</label>
                    <input class="input" type="text" id="HouseNumber" name="HouseNumber" asp-for="CheckoutInput.HouseNumber" />
                    <span asp-validation-for="CheckoutInput.HouseNumber"></span>
                </div>

                <div class="form-group">
                    <label for="ApartmentNumber">Apartment Number:</label>
                    <input class="input" type="text" id="ApartmentNumber" name="ApartmentNumber" asp-for="CheckoutInput.ApartmentNumber" />
                    <span asp-validation-for="CheckoutInput.ApartmentNumber"></span>
                </div>

                <div class="form-group">
                    <label for="ZipCode">Zip Code:</label>
                    <input class="input" type="text" id="ZipCode" name="ZipCode" asp-for="CheckoutInput.ZipCode" />
                    <span asp-validation-for="CheckoutInput.ZipCode"></span>
                </div>

                <div class="form-group">
                    <label>
                        <input  type="checkbox" asp-for="CheckoutInput.GenerateInvoice" />
                        Chcę fakturę
                    </label>
                    <span asp-validation-for="CheckoutInput.GenerateInvoice"></span>
                </div>

                <div class="form-group">
                    <label>
                        <input  type="checkbox" asp-for="CheckoutInput.IsCompany" />
                        Faktura dla firmy
                    </label>
                    <span asp-validation-for="CheckoutInput.IsCompany"></span>
                </div>

                <div class="form-group">
                    <label for="NIP">NIP:</label>
                    <input type="text" id="NIP" name="NIP" asp-for="CheckoutInput.NIP" />
                    <span asp-validation-for="CheckoutInput.NIP"></span>
                </div>

                <button type="submit">Realizuj/Zapłać</button>
            </form>


        </div>
    </section>

   
</body>
</html>

AirShop.WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Home page";
}
@*@{
	var isUserLoggedIn = ViewData["IsUserLoggedIn"] as bool? ?? false;
	var loggedInUserName = ViewData["LoggedInUserName"] as string ?? string.Empty;
}*@
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>My Website</title>
	<link rel="icon" href="./favicon.ico" type="image/x-icon">
	<link rel="stylesheet" href="~/css/index.css" asp-append-version="true">
</head>
<body>
    <div class="airglass">
        <p>AIRGLASS</p>
    </div>
		
	<div class="subtitle">
		<button type="button" onclick="location.href='@Url.Page("/AirGlassCatalogModel")'">BUY NOW</button>
	</div>
	<script>
		function showSidebar() {
			const sidebar = document.querySelector('.sidebar')
			sidebar.style.display = 'flex'
		}
		function hideSidebar() {
			const sidebar = document.querySelector('.sidebar')
			sidebar.style.display = 'none'
		}
	</script>
</body>
</html>

AirShop.WebApp/Pages/LoginModel.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AirShop.LoginPage</title>
    <link rel="stylesheet" href="./css/style1.css">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
</head>
<body>
    <div class="container-center">
        <div class="login-container">
            <form class="login-form" method="post">
                <div class="input-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" asp-for="LoginInput.Username">
                    <span asp-validation-for="LoginInput.Username" class="text-danger"></span>
                </div>
                <div class="input-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" asp-for="LoginInput.Password">
                    <span asp-validation-for="LoginInput.Password" class="text-danger"></span>
                </div>
                <div class="button-submit">
                    <button type="submit">LOGIN</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>